[package]
name = "squidtun"
version = "0.1.0"
authors = ["Alex Nichol <unixpickle@gmail.com>"]

[[bin]]
name = "squidtun"
path = "src/main.rs"

[dependencies]
clap = "2.31"
hyper = "0.11"
tokio_core = "0.1"
tokio_io = "0.1"
mio = "0.6"
