[package]
name = "squidtun"
version = "0.1.0"
authors = ["Alex Nichol <unixpickle@gmail.com>"]

[[bin]]
name = "squidtun-server"
path = "src/server/main.rs"

[dependencies]
clap = "2.31"
futures = "0.1"
hyper = "0.11"
mio = "0.6"
tokio-core = "0.1"
